include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/robots/ur10.yaml #inherits majority of robot config from ur10

logging:
  timestep: 1.0
  log_dir: /root/.logs

simulation:

  robot:
    # home and dims for Franka Panda (7 DOF)
    home: [-0.647003173828125, 0.529197096824646, -0.2042931467294693, -1.1539582014083862, 0.10314089804887772, 1.6733906269073486, 0]
    dims:
      q: 7  # generalized position
      v: 7  # generalized velocity
      x: 21 # state (q,v,aux)
      u: 7  # input
    joint_names:
      - "panda_joint1"
      - "panda_joint2"
      - "panda_joint3"
      - "panda_joint4"
      - "panda_joint5"
      - "panda_joint6"
      - "panda_joint7"
    tool_joint_name: "panda_joint8"
    base_type: fixed
    urdf:
      package: "upright_assets"
      path: "thing/urdf/panda.urdf"
      includes: ["$(find upright_cmd)/config/panda/assets/panda_spheres.urdf.xacro"]

  duration: 10.0
  arrangement: nothing

controller:

  robot:
    dims:
      q: 7
      v: 7
      x: 21
      u: 7
    x0: [-0.647003173828125, 0.529197096824646, -0.2042931467294693, -1.1539582014083862, 0.10314089804887772, 1.6733906269073486, 0, 0rep7, 0rep7]
    base_pose: [0, 0, 0]
    urdf:
      package: "upright_assets"
      path: "thing/urdf/panda.urdf"
      includes: ["$(find upright_cmd)/config/panda/assets/panda_spheres.urdf.xacro"]
    tool_link_name: "panda_link8"
    base_type: fixed

  waypoints:
    -
      time: 0
      position: [0.0, 1.0, 0.0]
      orientation: [0, 0, 0, 1]

  tracking:
    use_projectile: false

  obstacles:
    enabled: false

    # extra margin between objects
    # Important: this needs to be > 0 for the resulting constraint to be
    # differentiable
    minimum_distance: 0.02
  