include:
  -
    package: upright_cmd
    path: config/panda/_base.yaml

simulation:
  static_obstacles:
    enabled: true
    urdf: &obstacles_urdf
      package: "upright_cmd"
      path: "thing/urdf/obstacles.urdf"
      includes:
        - "$(find upright_cmd)/config/panda/assets/obstacles.urdf.xacro"

controller:
  obstacles:
    enabled: true
    urdf: *obstacles_urdf
    minimum_distance: 0.02
    collision_pairs:
      - ["panda_link4_0", "sphere_1_0"]
      - ["panda_link6_0", "sphere_1_0"]
      - ["panda_link7_0", "sphere_1_0"]
      - ["panda_link4_0", "sphere_2_0"]
      - ["panda_link6_0", "sphere_2_0"]
      - ["panda_link7_0", "sphere_2_0"]
      - ["panda_link4_0", "sphere_3_0"]
      - ["panda_link6_0", "sphere_3_0"]
      - ["panda_link7_0", "sphere_3_0"]
      